/* eslint-disable */
// AUTO-GENERATED by quicktype from questions-models.schema.json (do not edit).
// Source of truth: sockbowl-questions (./gradlew generateModelSchema).
// Regenerate: npm run codegen. Optionals stripped to match the API's
// always-present response shape.

export interface Packet {
    bonuses:    BonusElement[];
    difficulty: Difficulty;
    id:         string;
    name:       string;
    tossups:    TossupElement[];
    [property: string]: any;
}

export interface BonusElement {
    bonus: Bonus;
    id:    number;
    order: number;
    [property: string]: any;
}

export interface Bonus {
    bonusParts:  BonusPartElement[];
    id:          string;
    preamble:    string;
    subcategory: Subcategory;
    [property: string]: any;
}

export interface BonusPartElement {
    bonusPart: BonusPart;
    id:        number;
    order:     number;
    [property: string]: any;
}

export interface BonusPart {
    answer:   string;
    id:       string;
    question: string;
    [property: string]: any;
}

export interface Subcategory {
    category: Category;
    id:       string;
    name:     string;
    [property: string]: any;
}

export interface Category {
    id:   string;
    name: string;
    [property: string]: any;
}

export interface Difficulty {
    id:   string;
    name: string;
    [property: string]: any;
}

export interface TossupElement {
    id:     number;
    order:  number;
    tossup: Tossup;
    [property: string]: any;
}

export interface Tossup {
    answer:      string;
    id:          string;
    question:    string;
    subcategory: Subcategory;
    [property: string]: any;
}
