#!/usr/bin/env bash
# Generate the packet TypeScript types from the questions models' JSON Schema
# (sockbowl-questions is the single source of truth; it emits the schema via
# `./gradlew generateModelSchema`, synced here by scripts/sync-schema.sh).
set -euo pipefail
DIR="src/app/game/models/sockbowl"
SCHEMA="$DIR/questions-models.schema.json"
OUT="$DIR/packet-types.generated.ts"

npx --yes quicktype@26 --src-lang schema --lang typescript --just-types --top-level Packet "$SCHEMA" \
  | sed -E 's/\?:/:/g' | sed -E '/^=== .* ===$/d' > /tmp/packet-types.body.ts

{
  echo "/* eslint-disable */"
  echo "// AUTO-GENERATED by quicktype from questions-models.schema.json (do not edit)."
  echo "// Source of truth: sockbowl-questions (./gradlew generateModelSchema)."
  echo "// Regenerate: npm run codegen. Optionals stripped to match the API's"
  echo "// always-present response shape."
  echo "// quicktype 26 emits index signatures as [property: string]: unknown"
  echo "// (was: any) - narrow before use."
  echo ""
  cat /tmp/packet-types.body.ts
} > "$OUT"
echo "Generated $OUT"
